apiVersion: v1
kind: Service
metadata:
  name: git-sonic
  labels:
    app: git-sonic
spec:
  selector:
    app: git-sonic
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
